global:
  scrape_interval: 5s
  evaluation_interval: 10s

rule_files:
  - /etc/prometheus/alert.rules

scrape_configs:
  - job_name: app
    static_configs:
      - targets:
          - localhost

  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:4001

  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:4002

  - job_name: node_exporter
    static_configs:
      - targets:
          - node_exporter:4003
